export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;    

export const INVENTORY_WORKSHEET_NAME = process.env.NEXT_PUBLIC_INVENTORY_WORKSHEET_NAME;

export const ORDERS_WORKSHEET_NAME = process.env.NEXT_PUBLIC_ORDERS_WORKSHEET_NAME;

export const SPREADSHEET_ID = process.env.NEXT_PUBLIC_SPREADSHEET_ID;